/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesainUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author DELL 3442
 */
public class UPLOAD extends javax.swing.JFrame {

    /**
     * Creates new form UPLOAD
     */
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
    public UPLOAD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(428, 412));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(245, 229, 27));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("UPLOAD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 177, 58);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("←");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(380, 0, 50, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 100);

        jPanel2.setBackground(new java.awt.Color(164, 164, 164));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel2.setText("Kode Matakuliah");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 30, 110, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(150, 22, 250, 30);

        jLabel3.setText("Nama Matakuliah");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 70, 110, 14);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(150, 60, 250, 30);

        jLabel4.setText("Prodi");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 110, 110, 14);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(150, 100, 250, 30);

        jLabel5.setText("Semester");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 140, 110, 14);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(150, 136, 250, 30);

        jLabel6.setText("Path");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 220, 110, 14);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(150, 212, 250, 30);

        jButton1.setText("UPLOAD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(170, 260, 84, 30);

        jLabel7.setText("Kategori");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 180, 110, 14);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(150, 174, 250, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vectors Pack (Gabrielghdesign) (13).png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(-290, -20, 1070, 560);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 430, 320);

        setSize(new java.awt.Dimension(428, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String kodemk=jTextField1.getText();
        String nama=jTextField2.getText();
        String prodi=jTextField3.getText();
        String semester=jTextField4.getText();
        String kategori=jTextField6.getText();
        String path=jTextField5.getText();
        try{
            String sql = "INSERT INTO matakuliah"
            +"(kode_mk, nama_mk, prodi, semester, kategori, path)"
            +"VALUES (?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/banksoal_itera", "root", "");
            pst = con.prepareStatement(sql);
            pst.setString(1, kodemk);
            pst.setString(2, nama);
            pst.setString(3, prodi);
            pst.setString(4, semester);
            pst.setString(5, kategori);
            pst.setString(6, path);
            if (kodemk.equals("")) {
                JOptionPane.showMessageDialog(null, "Kode matakuliah Tidak boleh kosong");
            } else if (nama.equals("")) {
                JOptionPane.showMessageDialog(null, "Nama matakuliah Tidak boleh kosong");
            } else if (prodi.equals("")) {
                JOptionPane.showMessageDialog(null, "Prodi Tidak boleh kosong");
            } else if (semester.equals("")) {
                JOptionPane.showMessageDialog(null, "Semester Tidak boleh kosong");
            } else if (kategori.equals("")) {
                JOptionPane.showMessageDialog(null, "PKategori Tidak boleh kosong");
            } else if (path.equals("")) {
                JOptionPane.showMessageDialog(null, "Path Tidak boleh kosong");
            } else {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Upload Berhasil");
            }
             new Admin().setVisible(rootPaneCheckingEnabled);
        dispose();
            
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        Admin main = new Admin();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPLOAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPLOAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPLOAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPLOAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPLOAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
